export const palette = {
  white: "#FFFFFF",
  background: "#F5F7FA",
  surface: "#FFFFFF",
  surfaceMuted: "#EEF2F7",
  primary: "#203F78",
  brandOrange: "#F05A2A",
  primarySoft: "#E8EEF8",
  gray100: "#F2F4F7",
  gray200: "#DCE3EC",
  gray500: "#5E6B7D",
  gray700: "#405069",
  gray900: "#142033",
  black: "#000000",
  danger: "#B42318",
  success: "#18794E",
  warning: "#A15C00",
  info: "#1769AA",
} as const;

export const colors = {
  background: palette.background,
  surface: palette.surface,
  surfaceMuted: palette.surfaceMuted,
  border: palette.gray200,
  shadow: "rgba(0, 0, 0, 0.25)",
  overlay: "rgba(0, 0, 0, 0.45)",
  text: palette.gray900,
  textMuted: palette.gray500,
  textSubtle: palette.gray700,
  textOnPrimary: palette.white,
  primary: palette.primary,
  brandOrange: palette.brandOrange,
  primaryPressed: "#183464",
  primarySoft: palette.primarySoft,
  iconDefault: palette.primary,
  iconMuted: palette.gray500,
  serviceIconBackground: palette.primarySoft,
  tabActive: palette.primary,
  tabInactive: palette.gray500,
  danger: palette.danger,
  success: palette.success,
  warning: palette.warning,
  info: palette.info,
} as const;

export type AppColors = typeof colors;
